// Generates environment files from environment variables.
// Used by Vercel (and any CI/CD) at build time.
// Locally, keep your real values directly in environment.ts (gitignored).

const fs = require('fs');
const path = require('path');

const vars = [
  'SUPABASE_URL',
  'SUPABASE_ANON_KEY',
];

const missing = vars.filter(v => !process.env[v]);
if (missing.length > 0) {
  console.warn('⚠️  Missing env vars (app will build but Supabase will not work):', missing.join(', '));
}

const get = key => (process.env[key] ?? '').trim();
const isProd = process.env.NODE_ENV === 'production' || process.env.VERCEL_ENV === 'production';

// ALLOWED_EMAILS: comma-separated list of emails that can log in.
// Leave unset (or empty) to allow any authenticated user.
const allowedEmails = (process.env.ALLOWED_EMAILS ?? '')
  .split(',').map(e => e.trim()).filter(Boolean);

const envContent = `// Auto-generated by scripts/set-env.js — DO NOT EDIT MANUALLY
export const environment = {
  production: ${isProd},
  allowedEmails: ${JSON.stringify(allowedEmails)} as string[],
  supabase: {
    url: '${get('SUPABASE_URL')}',
    anonKey: '${get('SUPABASE_ANON_KEY')}',
  },
};
`;

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(envDir, { recursive: true });
fs.writeFileSync(path.join(envDir, 'environment.ts'), envContent);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), envContent);

console.log(`✅ environment files generated (production: ${isProd})`);
