// Generates environment files from environment variables.
// Used by Vercel (and any CI/CD) at build time.
// Locally, keep your real values directly in environment.ts (gitignored).

const fs = require('fs');
const path = require('path');

const vars = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = vars.filter(v => !process.env[v]);
if (missing.length > 0) {
  console.warn('⚠️  Missing env vars (app will build but Firebase will not work):', missing.join(', '));
}

const get = key => (process.env[key] ?? '').trim();
const isProd = process.env.NODE_ENV === 'production' || process.env.VERCEL_ENV === 'production';

const envContent = `// Auto-generated by scripts/set-env.js — DO NOT EDIT MANUALLY
export const environment = {
  production: ${isProd},
  firebase: {
    apiKey: '${get('FIREBASE_API_KEY')}',
    authDomain: '${get('FIREBASE_AUTH_DOMAIN')}',
    projectId: '${get('FIREBASE_PROJECT_ID')}',
    storageBucket: '${get('FIREBASE_STORAGE_BUCKET')}',
    messagingSenderId: '${get('FIREBASE_MESSAGING_SENDER_ID')}',
    appId: '${get('FIREBASE_APP_ID')}',
  },
};
`;

const envDir = path.join(__dirname, '..', 'src', 'environments');
fs.mkdirSync(envDir, { recursive: true });
fs.writeFileSync(path.join(envDir, 'environment.ts'), envContent);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), envContent);

console.log(`✅ environment files generated (production: ${isProd})`);
